[package]
name = "inject-browser-sdk-fuzz"
edition.workspace = true
version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.inject-browser-sdk]
path = "../lib/inject-browser-sdk"

[[bin]]
name = "fuzz-html-scanner"
path = "fuzz_targets/fuzz-html-scanner.rs"
test = false
doc = false
bench = false
