name: Development
on: [push, workflow_dispatch]

jobs:
  format:
    runs-on: ubuntu-22.04
    container:
      image: datadog/docker-library:dd-trace-cpp-ci
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/codestyle.sh lint

  build:
    needs: format
    runs-on: ubuntu-22.04
    container:
      image: datadog/docker-library:httpd-datadog-ci-2.4
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ls
      # - name: Configure
      #   run: cmake -B build -DHTTPD_SRC_DIR=httpd .
      # - name: Build
      #   run: |
      #     cmake --build build -j
      #     cmake --install build --prefix dist
      # - name: Export library
      #   uses:  actions/upload-artifact@v3
      #   with:
      #     name: mod_ddtrace_artifact
      #     path: dist/lib/mod_ddtrace.so

  # test:
  #   needs: build
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: datadog/docker-library:dd-trace-cpp-ci
  #   steps:
  #     - name: Import library from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: mod_ddtrace_artifact
  #     - run: pytest test --junitxml=out.xml

