name: Development
on:
  push:
  workflow_dispatch:
  schedule:
    # Run every other month to avoid 90-day GitHub artifact expiration
    - cron: '0 0 1 */2 *'

permissions:
  contents: read
  packages: read

jobs:
  format:
    runs-on: ubuntu-22.04
    container:
      image: datadog/docker-library:dd-trace-cpp-ci
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: ./scripts/codestyle.sh lint

  build:
    needs: format
    runs-on: ubuntu-22.04
    container:
      # Advanced by .gitlab/devcontainer-to-ghcr.yml after main builds.
      image: ghcr.io/datadog/httpd-datadog/devcontainer:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build
        run: make ci-build PRESET=ci-dev
      - name: Export library
        uses:  actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mod_datadog_artifact
          path: dist/lib/mod_datadog.so
          if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/datadog/httpd-datadog/devcontainer:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      DD_ENV: ci
      DD_API_KEY: ${{ secrets.DD_API_KEY_CI_APP }}
      DD_SERVICE: httpd-tests
      DD_CIVISIBILITY_AGENTLESS_ENABLED: true
      LLVM_PROFILE_FILE: /tmp/httpd.%p-%m.profraw
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: |
          pip install -r requirements.txt --break-system-packages
          pip install ddtrace --break-system-packages
      - name: Import library from build job
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: mod_datadog_artifact
          path: dist/lib
      - name: Run Smoke Tests
        run: pytest --ddtrace test/integration-test --module-path dist/lib/mod_datadog.so --bin-path /httpd/httpd-build/bin/apachectl --log-dir $(pwd)/logs -m smoke
      - name: Run Integration Tests
        run: pytest --ddtrace test/integration-test --module-path dist/lib/mod_datadog.so --bin-path /httpd/httpd-build/bin/apachectl --log-dir $(pwd)/logs -m ci
      - name: Generate code coverage
        run: |
          llvm-profdata merge -sparse /tmp/*.profraw -o /tmp/default.profdata
          llvm-cov export dist/lib/mod_datadog.so -format=lcov -instr-profile=/tmp/default.profdata -ignore-filename-regex=/httpd/ > coverage.lcov
      - name: Upload code coverage report to Datadog
        # See https://github.com/DataDog/coverage-upload-github-action/releases
        uses: DataDog/coverage-upload-github-action@2ba057033351887422f8eb0203d1990c3acbc8c5 # v1.0.4
        with:
          api_key: ${{ secrets.DD_API_KEY_CI_APP }}
          files: coverage.lcov
          format: lcov
