name: Release
on: [workflow_dispatch]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      # Advanced by .gitlab/devcontainer-to-ghcr.yml after main builds.
      image: ghcr.io/datadog/httpd-datadog/devcontainer:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Build
        run: make ci-build PRESET=ci-release
      - name: Export library
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mod_datadog_artifact
          path: dist/lib/mod_datadog.so
      - name: Export library (debug symbol)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mod_datadog_artifact-debug
          path: dist/lib/mod_datadog.so.debug
